#!/bin/env bash

set -e

install=(
  bc
  borgbackup
  breeze-cursor-theme
  cloc
  curl
  feh
  firmware-iwlwifi
  geary
  git
  gnome-disk-utility
  golang
  gparted
  keepassxc
  mpv
  mullvad-vpn
  ncdu
  network-manager-gnome
  nvi
  p7zip
  papirus-icon-theme
  pulseaudio-module-bluetooth
  python3-pip
  redshift
  sakura
  shellcheck
  slim
  stow
  tlp
  tmux
  transmission-gtk
  wkhtmltopdf
  xfce4-whiskermenu-plugin
  zathura-pdf-poppler
  zathura
)

uninstall=(
  acl
  ant-contrib
  ant-optional
  ant
  atril-common
  atril
  ca-certificates-java
  cups-client
  cups-pk-helper
  default-jre-headless
  default-jre
  efibootmgr
  espeak-ng-data
  exfalso
  firebird3.0-common-doc
  firebird3.0-common
  firebird3.0-server-core
  firebird3.0-utils
  firefox-esr-l10n-en-gb
  fonts-crosextra-caladea
  fonts-crosextra-carlito
  fonts-dejavu-extra
  fonts-dejavu
  fonts-font-awesome
  fonts-lato
  fonts-mathjax
  fonts-noto-core
  fonts-noto-mono
  fonts-noto-ui-core
  fonts-opensymbol
  fonts-roboto-slab
  fonts-sil-gentium-basic
  fonts-sil-gentium
  gimp-data
  gir1.2-atk-1.0
  gir1.2-atspi-2.0
  gir1.2-freedesktop
  gir1.2-gdkpixbuf-2.0
  gir1.2-gst-plugins-base-1.0
  gir1.2-gstreamer-1.0
  gir1.2-gtk-3.0
  gir1.2-gtksource-3.0
  gir1.2-javascriptcoregtk-4.0
  gir1.2-keybinder-3.0
  gir1.2-notify-0.7
  gir1.2-pango-1.0
  gir1.2-polkit-1.0
  gir1.2-secret-1
  gir1.2-soup-2.4
  gir1.2-webkit2-4.0
  gir1.2-wnck-3.0
  grub-efi-amd64-bin
  grub-efi-amd64-signed
  grub-efi-amd64
  gstreamer1.0-alsa
  gstreamer1.0-plugins-bad
  gstreamer1.0-plugins-ugly
  hddtemp
  hv3
  hyphen-en-us
  java-common
  javascript-common
  lm-sensors
  lp-solve
  mariadb-common
  mokutil
  mousepad
  mysql-common
  mythes-en-us
  node-normalize.css
  openjdk-11-jre-headless
  openjdk-11-jre
  orca
  packagekit-tools
  packagekit
  parole
  python3-brlapi
  python3-cairo
  python3-cups
  python3-cupshelpers
  python3-feedparser
  python3-gi-cairo
  python3-gst-1.0
  python3-louis
  python3-musicbrainzngs
  python3-mutagen
  python3-pyatspi
  python3-pyinotify
  python3-smbc
  python3-speechd
  python3-uno
  ristretto
  sane-utils
  shim-helpers-amd64-signed
  shim-signed-common
  shim-signed
  shim-unsigned
  sound-icons
  speech-dispatcher-audio-plugins
  speech-dispatcher-espeak-ng
  speech-dispatcher
  sphinx-rtd-theme-common
  synaptic
  system-config-printer-common
  system-config-printer-udev
  system-config-printer
  task-xfce-desktop
  tcl-tls
  tcl8.6
  tcl
  thunar-archive-plugin
  thunar-media-tags-plugin
  tk-html3
  tk8.6
  tk
  unzip
  update-inetd
  ure
  vim-common
  vim-tiny
  xarchiver
  xbrlapi
  xfburn
  xfce4-battery-plugin
  xfce4-clipman-plugin
  xfce4-clipman
  xfce4-cpufreq-plugin
  xfce4-cpugraph-plugin
  xfce4-datetime-plugin
  xfce4-dict
  xfce4-diskperf-plugin
  xfce4-fsguard-plugin
  xfce4-genmon-plugin
  xfce4-goodies
  xfce4-mailwatch-plugin
  xfce4-netload-plugin
  xfce4-notes-plugin
  xfce4-notes
  xfce4-places-plugin
  xfce4-sensors-plugin
  xfce4-smartbookmark-plugin
  xfce4-systemload-plugin
  xfce4-taskmanager
  xfce4-terminal
  xfce4-timer-plugin
  xfce4-verve-plugin
  xfce4-wavelan-plugin
  xfce4-weather-plugin
  xfce4-xkb-plugin
  xsane-common
  xsane
  xterm
  zenity-common
  zenity
)

sudo apt update
for package in "${install[@]}"; do
  sudo apt install "$package" -y
done
sudo apt purge ${uninstall[@]}
for package in "${install[@]}"; do
  sudo apt install "$package" -y
done
sudo apt autoremove -y
