#!/bin/env sh

set -eux

DOT_FILES="https://github.com/cristianrz/dotfiles.git"

# shellcheck disable=SC2016
dotfiles(){ /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree="$HOME" "$@"; }
echo 'alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"' >>~/.bashrc
# shellcheck disable=SC1090
echo ".dotfiles" >>.gitignore
git clone --bare $DOT_FILES ~/.dotfiles
cd "$HOME"
dotfiles config --local status.showUntrackedFiles no
dotfiles reset --hard
