#!/bin/sh

set -eu

test "$(id -u)" != "0" && echo 'Script must be ran as root' && exit 1

sudo apt --no-install-recommends install \
  compton \
  connman-gtk \
  dmenu \
  featherpad \
  firefox \
  geary \
  git \
  gnome-disk-utility \
  golang \
  keepassxc \
  lxappearance \
  lxrandr \
  ncdu \
  obconf \
  openbox \
  papirus-icon-theme \
  pavucontrol \
  pcmanfm \
  pulseaudio \
  python-gtk2 \
  python3-distutils \
  redshift \
  sakura \
  unzip \
  vim \
  wmctrl \
  xfce4-notifyd \
  xfce4-panel \
  xfce4-pulseaudio-plugin

sudo apt install \
  "xfce4-power-*" \
  xinit \
  xorg

mkdir -p /home/"$SUDO_USER"/.config/openbox/autostart
echo 'xfce4-panel &
pcmanfm --desktop &
redshift -l 50:1 &
compton -b -c &' > /home/"$SUDO_USER"/.config/openbox/autostart

wget -O /usr/local/bin/pacapt \
  https://github.com/icy/pacapt/raw/ng/pacapt

chmod 755 /usr/local/bin/pacapt

ln -sv /usr/local/bin/pacapt /usr/local/bin/pacman || true
