#!/bin/sh
#
# Setup needed for my bluetooth headphones to work

sudo apt install pulseaudio pulseaudio-module-bluetooth pavucontrol # bluez-firmware
sudo service bluetooth restart
sudo killall pulseaudio
