#!/bin/sh
#
# Installs the tor browser

set -e

cd /tmp || exit 1
if test ! -f tor-browser-*.tar.xz; then
	wget https://dist.torproject.org/torbrowser/9.0.1/tor-browser-linux64-9.0.1_en-US.tar.xz
fi
cd /opt || exit 1
rm -rf /opt/tor-browser*
tar xvf /tmp/tor-browser-linux64-9.0.1_en-US.tar.xz
ln -s /opt/tor-browser_en-US/Browser/start-tor-browser /usr/local/bin/tor-browser
chown -R "$(whoami):$(whoami)" /opt/tor-browser*
