#!/bin/sh

function add(){ sudo apt install --no-install-recommends "$@"; }

sudo apt install xorg xinit

sudo apt --no-install-recommends install \
  "xfce4-power-manager-*" \
  compton \
  dmenu \
  firefox \
  geary \
  gnome-disk-utility \
  golang \
  keepassxc \
  leafpaf \
  lxappearance \
  lxrandr \
  obconf \
  openbox \
  papirus-icon-theme \
  pavucontrol \
  pcmanfm \
  pulseaudio \
  python-gtk2 \
  python3-distutils \
  redshift \
  sakura \
  xfce4-notifyd \
  xfce4-panel \
  xfce4-pulseaudio-plugin

mkdir -p ~/.config/openbox/autostart
echo 'xfce4-panel &
pcmanfm --desktop &
redshift -l 50:1 &
compton -b -c &' > ~/.config/openbox/autostart
