#!/bin/sh
test "$(id -u)" != "0" && echo 'Script must be ran as root' && exit 1

sudo apt --no-install-recommends install \
  "xfce4-power-*" \
  compton \
  dmenu \
  firefox \
  geary \
  gnome-disk-utility \
  golang \
  keepassxc \
  leafpaf \
  lxappearance \
  lxrandr \
  obconf \
  openbox \
  papirus-icon-theme \
  pavucontrol \
  pcmanfm \
  pulseaudio \
  python-gtk2 \
  python3-distutils \
  redshift \
  sakura \
  xfce4-notifyd \
  xfce4-panel \
  xfce4-pulseaudio-plugin \
  xserver-xorg-core

sudo apt install xinit

mkdir -p ~/.config/openbox/autostart
echo 'xfce4-panel &
pcmanfm --desktop &
redshift -l 50:1 &
compton -b -c &' > ~/.config/openbox/autostart

wget -O /usr/local/bin/pacapt \
  https://github.com/icy/pacapt/raw/ng/pacapt

chmod 755 /usr/local/bin/pacapt

ln -sv /usr/local/bin/pacapt /usr/local/bin/pacman || true
